Update .travis.yml

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -43,8 +43,40 @@ jobs:
       
     - language: python
       python: 3.8
+      services: docker
+      env:
+      - COMPOSE_DIR=.
+      before_install:
+      # Stop MySQL.
+      - sudo service mysql stop
+
+      install:
+      # Install Ansible.
+      - pip install ansible docker
+
       script:
-      - python -c "print('Hi from Python!')"
+      # Build the Drupal environment.
+      - 'ansible-playbook main.yml --extra-vars "{build_arm32: false, build_arm64: false}"'
+
+      # Verify we get a response from the site.
+      - cd $COMPOSE_DIR
+      - docker-compose up -d
+      - |
+        attempts=0
+        max_attempts=60
+        echo "Waiting for Drupal to complete setup."
+        until $(curl --output /dev/null --silent --head --fail http://localhost/); do
+          if [ ${attempts} -eq ${max_attempts} ];then
+            echo "Timeout while waiting for Drupal to complete setup."
+            exit 1
+          fi
+          printf '.'
+          attempts=$(($attempts+1))
+          sleep 5
+        done
+      after_failure:
+      # Get logs after a failed run.
+      - docker-compose logs
 
     - language: node_js
       node_js: 12
